image:
  repository: democontainer01.azurecr.io/facesketchapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80